workflow:
  rules:
  - if: '$CI_OPEN_MERGE_REQUESTS != null && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "webide")'
    when: never
  - when: always


build-ct:
  stage: build
  image: gcr.si/cts/build-oci:1.3.0
  script: [ "/build.sh" ]
  variables:
    CTS_BUILD_CACHE_REPO: ${CI_REGISTRY_IMAGE}/cache
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    variables:
      CTS_BUILD_TAG: latest
  - if: $CI_COMMIT_TAG != null
    variables:
      CTS_BUILD_TAG: $CI_COMMIT_TAG
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    variables:
      BUILD_OCI_TAG: $CI_COMMIT_REF_SLUG
