version: '3.9'

name: matchmaker-prod

services:
  app-migrate:
    build: .
    image: gcr.si/frilan/dev/matchmaker:latest
    env_file:
      - .env.prod
    command: prisma migrate deploy
    depends_on:
      app-db:
        condition: service_healthy

  app:
    restart: always
    build: .
    image: gcr.si/frilan/dev/matchmaker:latest
    ports:
      - '80:3000'
    volumes:
      - ./config:/app/config
    env_file:
      - .env.prod
    healthcheck:
      test: curl -f http://localhost:3000
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      app-db:
        condition: service_healthy
      app-migrate:
        condition: service_completed_successfully

  app-db:
    image: postgres:16
    restart: always
    env_file:
      - .env.prod
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - app-db:/var/lib/postgresql/data

volumes:
  app-db:
