id: cs2new
name: CS2
enabled: true

password: true

min_teams: 2
max_teams: 2
min_team_size: 1
max_team_size: 5

join_regex: 'Accepting Steam Net connection.*steamid:(?<userId>[0-9]*)'
leave_regex: 'Steam Net connection #[0-9]* UDP steamid:(?<userId>[0-9]*).*closed by peer'

connection_string: 'steam://connect/${HOST}:${PORT}'

auto_start_game: 120

setup_commands:
  - 'mp_warmuptime 999999999'
  - 'mp_warmup_start'
start_game_command: 'mp_warmup_end'

deployment:
  type: server
  data:
    nest: 2
    egg: 18
    docker_image: ghcr.io/parkervcp/steamcmd:sniper
    startup: ./game/bin/linuxsteamrt64/cs2 -dedicated $( [ "$VAC_ENABLED" == "1" ] || printf %s ' -insecure' ) -ip 0.0.0.0 -port {{SERVER_PORT}} -tv_port {{TV_PORT}} -maxplayers {{MAX_PLAYERS}} $( [ "$RCON_ENABLED" == "0" ] || printf %s ' -usercon' ) +game_mode {{GAME_MODE}} +game_type {{GAME_TYPE}} +map {{SRCDS_MAP}} +hostname "{{SERVER_NAME}}" +sv_password "{{SERVER_PASSWORD}}" +rcon_password "{{RCON_PASSWORD}}" +sv_setsteamaccount {{STEAM_GSLT}
    limits:
      memory: 0
      swap: 0
      disk: 0
      io: 500
      cpu: 0
    environment:
      SRCDS_MAP: de_dust2
      SRCDS_APPID: 730
      MAX_PLAYERS: 64
      AUTO_UPDATE: 0
      TV_PORT: 27020
      VAC_ENABLED: 1
      RCON_ENABLED: 0
      RCON_PASSWORD: unused
      SERVER_NAME: FriLAN CS2
      SERVER_PASSWORD: '${PASSWORD}'
      STEAM_GSLT: A35C5AB344A7283F15FC8DC26899C0C6
      GAME_MODE: 1
      GAME_TYPE: 0
