id: minecraft
name: Minecraft

party_size: 4
max_players: 24

deployment:
  type: server
  data:
    egg: 3
    docker_image: ghcr.io/pterodactyl/yolks:java_17
    startup: 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}'
    limits:
      memory: 4096
      swap: 0
      disk: 0
      io: 500
      cpu: 0
    environment:
      SERVER_JARFILE: 'server.jar'
      BUILD_NUMBER: 'latest'
