id: unturned
name: Unturned
type: steam

party_size: 1
max_players: 50

password: true

join_regex: 'Connecting: PlayerID: ([0-9]*)'
leave_regex: 'Disconnecting: PlayerID: ([0-9]*)'
list_command: 'players'
list_regex: 'PlayerID: ([0-9]*).*Ping:'

deployment:
  type: server
  data:
    egg: 17
    docker_image: ghcr.io/parkervcp/steamcmd:debian
    startup: './Unturned_Headless.x86_64 -batchmode -nographics -bind 0.0.0.0 -port {{SERVER_PORT}} -GSLT {{GSLT}} -Name "{{SRV_NAME}}" -Password {{SRV_PW}} +InternetServer/{{SRV_ID}}'
    limits:
      memory: 4096
      swap: 0
      disk: 0
      io: 500
      cpu: 0
    environment:
      SRV_NAME: Unturned Server
      SRV_ID: UnturnedServer
      SRCDS_APPID: '1110390'
      GSLT: 905135FFDC753D2F7510693AE253F637
      LD_LIBRARY_PATH: ./Unturned_Headless_Data/Plugins/x86_64/
      AUTO_UPDATE: 1
      SRV_PW: '${PASSWORD}'
